language: node_js

node_js:
  - lts/*

before_install:
  - npm install -g codecov

after_script:
  - codecov

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  - echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc

deploy:
  # Publish to https://registry.npmjs.org/
  - provider: script
    script: npx lerna publish from-package --yes --registry=https://registry.npmjs.org/
    skip_cleanup: true
    on:
      branch: master

  # Publish to https://npm.pkg.github.com/
  - provider: script
    script: npx lerna publish from-package --yes --registry=https://npm.pkg.github.com/
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    - secure: C8jfCrZwEqnL8mtB5FbJArvo8t7/jNS8yMIchVApR3HGhdEgxPXJHw6kKlrbkoqcgd8DHd7hw9emg7Tw7EYQbTXrRgLJMmL2rqexetTMrynlqmzFnVw/G0pw6YGhsDOtTpWu1sLFzMMkDYqFRBcQYA087PP0W1Ud6s7wHi1PBUD+b5sQFgrB+9YG2EvcePSEXBdSC0lk3Fi0wkqU9YIM+C3lzX+CxQfYSkNi3bPP6EpBuempf/upHN/0oPXly2VVh3jS9g1i7k3rr4fLuGo6mgvTKYAo/6p9SDWXVbYn08fuLlstgD2PxDhLZkKDw9Qbk7GI26Y/oRjCpHZK+RDox4FwwQRHEzMdMREAW3d5AwP5FKjrc1rQkQvE4f0r4saW6Y2GRpQiYrCXA6XaD/fgQXypFXLLGoEXnsUBauWOTMeyFFR/jDjjXtF12YsXh7fOAoApsyKjtlcgBaw+6LYObD+p2h9xhQ0oaQsnSyQDj8HdbDWp6JKq0u4AGd86gSz2LHkW7/qwyjMt/CXRPDOwbsRA6u6ZjdDvvZ0sXYHaEBn1RhhfREFEGNj73IS2ROf8SdkC+xOqKJtphwI55Nt9OHKODPDQi/qj+ER6i9tyE7GnN+UDOR1ER8VEKlBxzQ+wZitc6seqCgP43UZMkF3fHJcXMa1vpwh74W7ja8nvUzE=
    - secure: H6j6fvmJj5mTu1KsxV8d407N4FVac6xqKjuorUR6l9yJUt5b96kPrqacz1FiEbZhkvAKveIlYC2L0TvQpgHcZG6k3L5fPwejizetvijl3t9TE3fxCMhqIqQ2L5UHTCMZyshY9MAeVyPTpYk8f+1p+xLzFMdl8Z1ZW1so1e0PbXrlT+dK60WCQMV36cS3GU5QFJVlMvgDgkDlbIL75zImC4UL9V5xvgL4dTNwt2urVUyM5Vj6Z/Io4/fiOAyFcOlfMME84tVtEArNYn5BTiyTD1IMeVlA2clMrotB73iIKRfRSfTbGx9J7Wl1Zn5i84bIyCpSeJkDlifhShnG/qSnmCqcS3L1BxZqu+/0UZ1eroVcM/YtD0PcfrZByQAk8uM+PuL/eNGiO7hY5G8pasFSBv+0ZkNY99kp27qwyVVcuR9Mq/crrrQC/9JOwc9kSrCpzCquROVRMYMBRqxOYUezt4WL5bjn9otBm5i/8cb9clw10LRnXRnrkzNtqcMbs8xk2t2rc10ynEevtitfBuzdQeTF16vueZJo4sI9PxzLnemCywERGBEwIEFBQJ1+MMyt17KdDLS+Od4UQU++B+hAGNbyGqyqUl/VKYt9L8sy8GmJQCPYXwLrv0S41IIHs7Fdw/Fi+GyGI2LAWSh5Gbc7stIF1QXSoOS55AtaCjeGc4s=
