language: node_js

node_js:
  - "lts/*"

before_install:
  - npm install -g codecov

after_script:
  - codecov

before_deploy: "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc"

deploy:
  provider: script
  script: "npx lerna publish from-package --yes"
  skip_cleanup: true
  on:
    branch: master
